[package]
name = "meme-management"
version = "0.0.0"
description = "A Tauri App"
authors = ["mslxl <i@mslxl.com>"]
license = "AGPL"
repository = ""
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.53.1"
tauri-build = { version = "1.3", features = [] }

[dependencies]
tauri = { version = "1.3", features = ["dialog-all", "protocol-all", "shell-open", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
tokio = { version = "1.28.0", features = ["rt", "rt-multi-thread", "fs" ,"io-util", "io-std", "macros"] }
serde_json = "1.0"
once_cell = "1.17.1"
sha256 = "1.1.3"
base64 = "0.21.0"
directories = "5.0.1"
human-panic = "1.1.4"
libc = "0.2.143"
encoding-next = "0.3.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
